[package]
name = "yage_core"
version = "0.1.0"
edition = "2021"

[dependencies]
yage_sys = { path = "/home/jack/Documents/yage/yage_sys" }


[features]
std = []
default = ["std"]
async_support = []
default_listeners = []
unstable = []
